name: Upload to S3

on:
  workflow_dispatch:
    inputs:
      versionName:
        description: "Version name to publish"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Set up DEST_DIR
        run: echo "DEST_DIR=canary-versions/${{ github.event.inputs.versionName }}" >> $GITHUB_ENV

      - uses: jakejarvis/s3-sync-action@master
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_CODUX_HOSTING_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_CODUX_HOSTING_S3_BUCKET_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_CODUX_HOSTING_S3_BUCKET_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_CODUX_HOSTING_S3_BUCKET_REGION }}
          SOURCE_DIR: "dist-app"
          DEST_DIR: ${{ env.DEST_DIR }}
